### ISSUE TITLE
Putting space as the only character in ‘local authorities’ or ‘English counties’ brings up predictive search terms that include a space

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#10]
I would expect this to do nothing, like Google search.  Further more Google seems to ignore leading whitespace so ‘a’ or ‘             a’ in the field both bring up Amazon, Argos etc.

**Comment by ijdickinson** [comment]
I've made some changes here, but it may not be the final fix. First, I've increased the minimum search term to two characters, so a single space won't bring up anything. I don't want to filter spaces out of the input altogether, because "st " (i.e. s-t-space) would be a useful term for finding places like St Albans.

I also increased the length of the suggestion list from 8 to 15. It's possible to display all auto-completion options, but even with a two character search term there can be 40+ completions for common terms, so the list becomes a bit mind-boggling. I've not found a way so show a label like "+ 8 more" at the end if there are additional completions, but I might put in a feature request to the library that I'm using to add that, or create my own!

Anyway, I'd appreciate it if you could have a look and say whether I've done enough for now or whether we need to leave this issue open for more improvements.

**Comment by marklunn** [comment]
I've had a look at this and these changes look good.  Only thing I'd mention is that If you type a space(s) and then start typing a valid county then nothing comes up in the search. When trying this with local authorities it works with one space but not with more than one.  Is there a way to ignore all prefix spaces?

**Comment by ijdickinson** [comment]
I've changed the code to make matching smarter

**Comment by marklunn** [comment]
When typing spaces before letters the search now ignores the prefix spaces and shows search results - happy to close.
