### ISSUE TITLE
Selection of house type applies to all graphs

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#102]
I'm almost positive this is just a site is still in development thing - but I was expecting if I selected a house type i.e. detached it would only apply on the graph it was selected on.

As it currently stands if you selected detached property it applies to all graphs with the detached property index. 

Can you confirm this is not the expected behavior of the final product?

**Comment by ijdickinson** [comment]
That's the expected behaviour. It matches the current UX for UKHPI, and also the non-Javascript behaviour for the new app.

Bearing in mind that an index is one of average price, index, monthly % change and yearly % change, if you think about the state, at the moment the user can select:

    5 property types + 4 indices + 
    2 funding status + 4 indices +
    2 property status + 4 indices +
    2 buyer status + 4 indices +
    3 sales volumes
    = 30

So because choosing a theme to be visible and choosing which indices are selected within that are independent, 30 states need to encodable in the URL. 

If we allow different indices to be selectable for different stats within the them, we'd have a lot more potential states to encode, and the URL would become very complicated!

We should see how users get on with the user test next week. If it's a problem in practice, I'll see what solutions there might be, but for now I'd prefer to leave as-is.

**Comment by MalcolmShazell** [comment]
Happy with what you say - it does make sense - lets see how the users find it - I know we have some that haven't used the old system or been involved so won't have my assumptions built in

**Comment by MalcolmShazell** [comment]
user testing showed this behaviour was fine.
