### ISSUE TITLE
Accessability - A014 use the page with keyboard input only

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#185]
when tabbing through the app - the functions 
see data graph
see data table 
download data
compare location 

are skipped over

**Comment by ijdickinson** [comment]
@MalcolmShazell There is an issue here, but it's not quite bad as not being possible to navigate at all.

Taking the first graph unit as an example, if the tab focus is on the `flats and maisonettes` option, the next press of the tab key will put the focus on `see data graph`. However, the CSS isn't quite right because the orange element-has-focus border isn't all around the tab header element.

From there, pressing tab will go the location selector in the next graph unit below, but pressing left and right arrow keys will navigate among the `see data table`, `download data`, etc, tabs.

So it *is* possible to fully navigate with the keyboard, except that (a) the CSS isn't always as clear as it could be, and (b) you have to use the arrow keys as well as the tab key. I don't know if (b) is mandatory to fix or not. Guidance?

**Comment by MalcolmShazell** [comment]
I think we are good here - the key is fully able to navigate via keyboard which we can do that meets W3C I will issue guidance to the support staff so the can advise if they have a query
