### ISSUE TITLE
data table not showing 

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#205]
when you select 'see data table' on the graph you are only given the print data table option

**Comment by MalcolmShazell** [comment]
this might be linked, the data table for compare locations is also not showing

**Comment by ijdickinson** [comment]
@MalcolmShazell I now understand what's happening, although not entirely why. The data-table component that I'm using, `el-table`, has decided through some combination of library version updates and build script updates, to stop, as it were, being visible in the UI. This is, to put it mildly, inconvenient.

I have a partly-completed solution, which is to not use `el-table` and just render the tables in HTML myself. I have proof-of-concept code working, I just need to finish off the styling so that it looks similar to the old table.

Sadly, I'm not sure I'm going to get that released in time for  you to test before you start your leave period.

**Comment by MalcolmShazell** [comment]
@ijdickinson  - if you get it done when you can, I was going to do the full regression test at the weekend but i'll wait until that fix is in - I should be free from Thursday 25th to do the regression test (we've budgeted me doing the regression tests over my leave period.) but I have a visitor from sat afternoon until thursday morning so i'm unable to find the time while they are down.

**Comment by ijdickinson** [comment]
@MalcolmShazell There's a fixed version on the dev server, when you have time to kick the tyres a bit!

**Comment by MalcolmShazell** [comment]
will do sir

**Comment by MalcolmShazell** [comment]
data now displaying
